telegram:
  bot_token: 5589990285:AAHrryfcpwPV6eIOGVpRcw0IZIu26kO0Lms
database:
  user: postgresql
  password: password
  host: 127.0.0.1
  port: 5432
  database: postgres
calendar:
  calendar_id: 2664c763687f1077b7b2cca00fd239bf598400f65e539e9ad4c913627b20e3eb@group.calendar.google.com